### ISSUE TITLE
Please add https://qiskit.org/ecosystem/neko/ to the project's About section

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit-neko#30]
Here:

<img width="327" alt="Screenshot 2023-08-16 at 10 41 48 AM" src="https://github.com/Qiskit/qiskit-neko/assets/14852634/c00595c0-5b78-4aac-a64c-06acfaf686be">

Also the README needs to use the ecosystem link:

https://github.com/Qiskit/qiskit-neko/blob/e2cbd7cb9794cac31e7ecbae426c27e86713674d/README.md?plain=1#L6

Or it'd be fine to remove it imo.

cc @mtreinish

**Comment by arnaucasau** [comment]
Gentle bump on this issue :)

**Comment by Eric-Arellano** [comment]
Replaced by https://github.com/Qiskit/qiskit-neko/issues/38
