### ISSUE TITLE
Set up GitHub Pages and update the About section

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/qiskit-neko#38]
### Instructions 
The project now has the documentation deployed in a branch called [gh-pages](https://github.com/Qiskit/qiskit-neko/tree/gh-pages), but we need to set up the repo to use GitHub Pages by following the next 5 steps. Once the GitHub Pages is set up please update the repo's About section to display the new link.

1. Navigate to your site's repository
2. Click `Settings`
3. Go to `Pages`
4. Select `Deploy from a branch`, under the `Source` section on `Build and deployment`
5. Select the `gh-pages` branch and the `/ (root)` folder in the `Branch` section on `Build and deployment`

![GitHubPages-example](https://github.com/Qiskit/ecosystem/assets/47946624/520f4f0c-905a-4a4f-b918-a580a953e80d)

The default URL where you can find your site is https://qiskit.github.io/qiskit-neko

For further information, you can see the [GitHub Pages Quickstart](https://docs.github.com/en/pages/quickstart#creating-your-website) and https://github.com/Qiskit/ecosystem/issues/578.

**Comment by jakelishman** [comment]
I've just set up things up for GH pages, but I was just on my phone so let me know if I missed something.

**Comment by Eric-Arellano** [comment]
Looks great. Thanks! We'll set up redirects from qiskit.org.
